### ISSUE TITLE
How to use RA2 with this??

### ISSUE THREAD

**Issue by salvadorc17** [phrohdoh/OpenRA#11]
Waht should i do to use RA2 with this, where to get content, and how to put into this together..

**Comment by phrohdoh** [comment]
You need to clone this repo, build it, and place `RA2.mix`, `theme.mix`, and `language.mix` into your content directory.

Come to #orcaware on the freenode IRC network if more help is needed.

**Comment by salvadorc17** [comment]
Which one is the content directory?? mods/ra2??

**Comment by phrohdoh** [comment]
https://github.com/OpenRA/OpenRA/wiki/Game-Content#manual-installation

**Comment by salvadorc17** [comment]
Got this error when compiling OpenRaModsCommon
Error   1   An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type  OpenRA.Mods.Common

**Comment by phrohdoh** [comment]
This isn't an issue with RA2, please report any compilation errors with system information at https://github.com/OpenRA/OpenRA/issues or join the irc channel for openra.

**Comment by salvadorc17** [comment]
But the issue is for your version of OpenRa.common compilation, not for original

**Comment by phrohdoh** [comment]
The `OpenRA.Mods.Common` in RA2 is exactly the same as upstream.

Compilation works just fine for me on RA2:

```
in openra
$ make
CSC fixheader.exe
CSC OpenRA.Game.exe
CSC OpenRA.Renderer.Sdl2.dll
CSC OpenRA.Renderer.Null.dll
CSC mods/common/OpenRA.Mods.Common.dll
CSC mods/ra/OpenRA.Mods.RA.dll
CSC mods/cnc/OpenRA.Mods.Cnc.dll
CSC mods/d2k/OpenRA.Mods.D2k.dll
CSC mods/ts/OpenRA.Mods.TS.dll
CSC mods/ra2/OpenRA.Mods.RA2.dll
CSC OpenRA.Utility.exe
```
