### ISSUE TITLE
OpenRA cannot start, OpenTK requiered??

### ISSUE THREAD

**Issue by salvadorc17** [phrohdoh/OpenRA#12]
OpenTK.Graphics.GraphicsContextMissingException: No context is current in the calling thread (ThreadId: 1).
   en OpenTK.Graphics.GraphicsBindingsBase.LoadEntryPoints()
   en OpenTK.Graphics.OpenGL.GL.LoadAll()
   en OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode) en C:\Users\Usuario\Documents\Visual Studio 2008\OpenRA-ra2-master\OpenRA.Renderer.Sdl2\Sdl2GraphicsDevice.cs:línea 87

**Comment by phrohdoh** [comment]
Again, this is upstream.
