### ISSUE TITLE
Fog is using Shroud sprite.

### ISSUE THREAD

**Issue by phrohdoh** [phrohdoh/OpenRA#16]
This makes it appear ingame as if fog is broken and that (immediate) regrowing shroud exists.

I'm not sure how to fix this yet.

**Comment by LavenderMoon** [comment]
Maybe apply transparency to the fog layer or something?

**Comment by GraionDilach** [comment]
fog.shp is the fog, shroud.shp is the shroud - what's the problem actually?

**Comment by phrohdoh** [comment]
@GraionDilach Exactly what the title says.

Even though we have this setup the wrong sprites are being used.
https://github.com/Phrohdoh/OpenRA/blob/ra2%23master/mods/ra2/sequences/misc.yaml#L294-L298

**Edit**:
I just thought about the fact that Shroud in other mods may use a transparent palette.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/pull/9396 for a fixed shroud/fog palette/sprite setup you can test in the editor.

**Comment by phrohdoh** [comment]
This was fixed in #17.
