### ISSUE TITLE
Cannot build missile silo

### ISSUE THREAD

**Issue by ghost** [phrohdoh/OpenRA#27]
Even with Build Everything, I cannot find a missile silo on the build panes.

Revision: 41d9a20

**Comment by phrohdoh** [comment]
It is commented our currently due to lack of a nuke superweapon.
But good report nonetheless.

**Comment by ghost** [comment]
Seems strange, given that the other support powers aren't implemented but the buildings were.

**Comment by phrohdoh** [comment]
IIRC something was causing the game to crash with the nuke so we just commented it out as a terrible _fix_.

**Comment by MustaphaTR** [comment]
According to commented out part at sequence file. It was saying ngmisl is not a vaild shp file. Possibly becuase of it is empty file and in fact ngmisl_e is used. I'm going to add it.

**Comment by MustaphaTR** [comment]
That's wierd, they looks complately off from tiles. Do you have any idea why?

![nuke](https://cloud.githubusercontent.com/assets/7933210/10867485/3b8b31e2-806d-11e5-83ca-b20d9d6466f5.png)

Edit: Whatever, i solved it.

**Comment by MustaphaTR** [comment]
Fixed by #64. I think we can close this.

**Comment by phrohdoh** [comment]
Correct.
