### ISSUE TITLE
Chrono Legionnaires are not buildable

### ISSUE THREAD

**Issue by ghost** [phrohdoh/OpenRA#32]
These are the most OP unit in the game!

Revision: 41d9a20

**Comment by phrohdoh** [comment]
Not buildable as in their prereqs are incorrect, or they are not implemented? etc.

**Comment by ghost** [comment]
Not implemented, I think. I don't see them on the menu.

**Comment by phrohdoh** [comment]
Check the yaml, the build palette has all sort of conditional logic for displaying actor cameos.

**Comment by ghost** [comment]
Will do after I go through other stuff.

**Comment by Mailaender** [comment]
Fixed by https://github.com/OpenRA/ra2/pull/258.
