### ISSUE TITLE
Harriers/Black Eagles are not implemented

### ISSUE THREAD

**Issue by ghost** [phrohdoh/OpenRA#34]
I cannot build them at all.

Revision 41d9a20

**Comment by phrohdoh** [comment]
Ref https://github.com/Phrohdoh/oramod-ra2/issues/1

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/ra2/pull/60.

**Comment by abcdefg30** [comment]
OpenRA/ra2#60 was merged, this can be closed then, I guess.
