### ISSUE TITLE
Grand Cannon construction animation is buggy

### ISSUE THREAD

**Issue by ghost** [phrohdoh/OpenRA#40]
Occurred on 41d9a20

It appears to draw both the fully-complete grand cannon from the first frame, as well as the construction animation behind it.

**Comment by MustaphaTR** [comment]
Voxel Turrets starts to be rendered before buildup anim is completed. This happens to TS Nod Laser Turret, possibly to Flak and Patriot there.

**Comment by abcdefg30** [comment]
This seems to be fixed in the latest version of [OpenRA/ra2](https://github.com/OpenRA/ra2).

**Comment by Mailaender** [comment]
This was fixed in https://github.com/OpenRA/OpenRA/pull/10222.
