### ISSUE TITLE
Buildings have weird z-ordering.

### ISSUE THREAD

**Issue by ghost** [phrohdoh/OpenRA#60]
Some known examples:
- An allied War Factory will be drawn on top of a vehicle stationed immediately southwest of it.
- Man buildings are inconsistently drawn above and/or below the overlay for the Iron Curtain support power.

**Comment by penev92** [comment]
There is no proper Z-sorting in OpenRA yet. That is still being worked on.

**Comment by phrohdoh** [comment]
Z-Sorting does exist in the way of `ZOffset` for sequences.

**Comment by Mailaender** [comment]
Reverse duplicate of https://github.com/OpenRA/ra2/issues/127.
